config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('newsletter.urls',namespace='newsletter')),
]

newsletter/urls.py
from django.urls import path
from . import views

app_name = 'newsletter'

urlpatterns = [
    path('', views.index,name='index'),
    path('subscibe/',views.subscribe,name='subscribe'),
    path('unsubscribe/',views.unsubscribe,name='unsubscribe'),
    path('validate/',views.validate_email,name='validate-email'),

    # handles Token Validation
    # use confirm-subscription/auth/<str:token>/ instead of token-validation/auth/<str:token>/
    path('token-validation/auth/<str:token>/',views.validate_confirmation_token,name='validate-token'),
    path('thank-you/<str:token>/',views.thank_you,name='thank-you'),
]

newsletter/models.py
import datetime
from django.conf import settings
from django.utils import timezone
from dateutil.relativedelta import relativedelta


from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import BadHeaderError,send_mail
from django.template.loader import render_to_string,get_template

from .utils import date_duration
from .token import activation_token

from django.db import models




class NewsLetter(models.Model):
	''' NewsLetter Model.
	
	@@attr. 

	email 			- Email 
	ip 	  			- Ip Address
	is_subscribed  	- DateTime (indicate whether subscription is confirmed)
	@@methods.
	
	 '''
	email 					= models.EmailField(max_length=170)
	ip     					= models.GenericIPAddressField()
	is_subscribed			= models.DateTimeField(blank=True,null=True) # new

	created 				= models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering 			= ('-created',)
		verbose_name 		= 'NewsLetter'
		verbose_name_plural = 'NewsLetters'


	def __str__(self):
		return self.email


	@classmethod
	def unconfirmed_newsletters(cls):
		return cls.objects.filter(is_subscribed__isnull=True)


# Exceptions
class ActivationError(Exception):pass
class ActivationCodeExistError(Exception):pass

class Activation(models.Model):
	'''Activation Model'''
	token 					= models.CharField(max_length=250,blank=True,null=True,unique=True,editable=False)
	newsletter 				= models.OneToOneField(to=NewsLetter,on_delete=models.CASCADE) 
	expired 				= models.DateTimeField(blank=True,null=True)
	is_sent 				= models.BooleanField(default=False)

	created 				= models.DateTimeField(auto_now_add=True)


	class Meta:
		ordering 	= ('-created',)
		verbose_name = 'Activation'
		verbose_name_plural = 'Activations'


	def __str__(self):
		return str(self.newsletter.email)

	def save(self,*args,**kwargs):
		super(Activation,self).save(*args,**kwargs)
		



	def send(self,request=None):
		'''
		TODO:
		1. Send Email via SendGrid & MailChimp (learning purposes)
		2. Find a Better Way to generate validation link - DONT HARD CORD IT !
		'''
		domain  = get_current_site(request).domain
		link_url = 'http://{0}/token-validation/auth/{1}/'.format(domain,self.token)

		subject = 'Confirm Subscription'
		message = "{1} to confirm subscription".format(domain,link_url)
		from_email = settings.DEFAULT_FROM_EMAIL
		to_email = self.newsletter.email

		try:
			send_mail(subject,message,from_email,[to_email],fail_silently=True)
		except BadHeaderError:
			pass
		


	@classmethod
	def create_activation(cls,instance):
		# create and returns activation object.
		return cls.objects.create(token = activation_token(),
							newsletter = instance,
							expired=date_duration(),
							is_sent=True)



	def has_expired(self):
		return timezone.now() > self.expired

	has_expired = property(has_expired)

newsletter/forms.py
from .models import NewsLetter
from django import forms


class SubscribeForm(forms.ModelForm):
	email 	   = forms.EmailField(label='',required=True,help_text='kindly hit ENTER when you fill input.',widget=forms.EmailInput())
	class Meta:
		model  = NewsLetter
		fields = ('email',)

	def __init__(self,*args,**kwargs):
		super(SubscribeForm,self).__init__(*args,**kwargs)
		self.fields['email'].widget.attrs.update({'placeholder':'eg.edward@bimmeo.com'})

newsletter/views.py
from django.template.response import TemplateResponse
from django.views.decorators.http import require_http_methods
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponse,Http404
from django.shortcuts import redirect,get_object_or_404
from django.http import JsonResponse
from django.contrib import messages
from django.conf import settings
from django.urls import reverse

from .models import NewsLetter,Activation
from .utils import visitor_ip_address
from .decorators import ajax_required
from .forms import SubscribeForm



def index(request):
	# index view renders form
	form = SubscribeForm()
	return TemplateResponse(request,'newsletter/subscribe.html',{'form':form})



def thank_you(request,**kwargs):
	''' renders a page with a message `THANK YOU ` '''
	return TemplateResponse(request,'newsletter/thank_you.html',{})




@ajax_required
@require_http_methods(["POST"])
def subscribe(request):
	# subscribe view handles submittion
	email = request.POST.get('content').strip()
	ip = visitor_ip_address(request)
	newsletter,created = NewsLetter.objects.get_or_create(email = email,ip=ip)
	if created:
		Activation.create_activation(newsletter).send(request)
	return JsonResponse({'data':created})



@require_http_methods(["POST"])
def unsubscribe(request):
	'''
	@approah
	use same processes for subscription.
	'''
	pass




@require_http_methods(["POST"])
@ajax_required
def validate_email(request):
	# validates email on KeyUp (ClientSide Js)
	email = request.POST.get('content').strip()
	is_taken = NewsLetter.objects.filter(email__iexact=email).exists()
	data = {'data':is_taken}
	return JsonResponse(data)




def validate_confirmation_token(request,token = None):
	# validate token after user clicks link to this place
	# after successful validation redirect user to thank you view with the token passed

	activation_obj = get_object_or_404(Activation,token__iexact=token,is_sent=True)
	# newsletter = get_object_or_404(Activation,token__iexact=token).newsletter
	if activation_obj.has_expired:
		return HttpResponse('Activation code is invalid.')
	else:
		from django.utils import timezone
		activation_obj.newsletter.is_subscribed = timezone.now()
		activation_obj.newsletter.save()
		activation_obj.delete() # remove activation object from db
		return redirect(reverse('newsletter:thank-you',kwargs={'token':activation_obj.token}))

newsletter/templates/newsletter/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>NewsLetter Subscription</title>
    <!-- Bootstrap Version 4.1.x -->
    <link rel="stylesheet" href="{% static 'css/vendors/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendors/line-awesome/line-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>

<style type="text/css">
body{
  background-image: url({% static 'img/bck-pattern.png' %}) !important;
  background-size: cover !important;
  background-position: center center !important;
  background-repeat: no-repeat !important;
  height: 100vh !important;
}	

</style>

<!-- content section -->
<section class="container">
{% block content %}
	
{% endblock %}
</section>
<!-- /content section -->

<script type="text/javascript" src="{% static 'js/vendors/jquery/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendors/bootstrap/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>

</html>

newsletter/templates/newsletter/subscribe.html
{% extends 'newsletter/layout.html' %}
{% load crispy_forms_tags %}

{% block content %}

	<section class="row">
		<section class="col-lg-8 offset-lg-2 p-col">
			<section class="wrapper shadow-sm">
				<h2 class="text-center">Subscribe for NewsLetter</h2>
				<h6 class="text-center">Only one email per week. I promise <span style="font-size: 16px;">🙂</span></h6>
				<form action='{% url "newsletter:subscribe" %}' method="POST">
					{% csrf_token %}
					{{form|crispy}}
					<div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div>
				</form>	
			</section>
		</section>
	</section>

{% endblock %}

newsletter/templates/newsletter/thank_you.html
{% extends 'newsletter/layout.html' %}

{% block content %}

	<section class="row">
		<section class="col-lg-12 mt-4">
			<section class="message shadow-sm" style="height: 100px;
													text-align: center;
													line-height: 100px;
													background: #1bcece;">
				<h2 style="color: #ffffff;
    font-weight: 600;
    font-size: 2em;">Thank You for Subscribing.</h2>
			</section>
		</section>
	</section>

{% endblock %}